# Generated by Django 3.2 on 2021-04-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Unique_Squirrel_ID', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('Shift', models.CharField(max_length=1000, null=True)),
                ('Date', models.DateField(null=True)),
                ('Age', models.CharField(max_length=1000, null=True)),
                ('Primary_Fur_Color', models.CharField(blank=True, max_length=1000, null=True)),
                ('Location', models.CharField(blank=True, max_length=1000, null=True)),
                ('Specific_Location', models.CharField(blank=True, max_length=1000, null=True)),
                ('Running', models.BooleanField(blank=True)),
                ('Chasing', models.BooleanField(blank=True)),
                ('Climbing', models.BooleanField(blank=True)),
                ('Eating', models.BooleanField(blank=True)),
                ('Foraging', models.BooleanField(blank=True)),
                ('Other_Activities', models.CharField(blank=True, max_length=1000, null=True)),
                ('Kuks', models.BooleanField(blank=True)),
                ('Quaas', models.BooleanField(blank=True)),
                ('Moans', models.BooleanField(blank=True)),
                ('Tail_Flags', models.BooleanField(blank=True)),
                ('Tail_Twitches', models.BooleanField(blank=True)),
                ('Approaches', models.BooleanField(blank=True)),
                ('Indifferent', models.BooleanField(blank=True)),
                ('Runs_From', models.BooleanField(blank=True)),
            ],
        ),
    ]
