# Generated by Django 3.2 on 2021-04-11 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='adopt_me_if',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='first_thing_people_notice_about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='friday_night',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AdoptRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_ts', models.DateTimeField(auto_now_add=True)),
                ('adopter', models.EmailField(help_text='Email of adopter', max_length=254)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pet')),
            ],
        ),
    ]
